"angular-dashboard": {
  "architect": {
    "build": {
      "options": {
        "outputPath": "dist/angular-dashboard/browser"
      }
    },
    "serve": {
      "options": {
        "browserTarget": "angular-dashboard:build"
      }
    }
  }
}
